version: '3'

volumes:
    postgres:

networks:
    main_net:

services:
  postgres:
    image: postgres:9.6.10
    # ports:
    #   - 5432:5432
    env_file: ./postgres/.env
    volumes:
        - postgres:/var/lib/postgresql/data
    networks:
      - main_net 
  botpress:
    image: aquintero446/botpress-demo_botpress
    restart: always
    build: ./botpress
    env_file: ./botpress/.env
    command: "./bp"
    volumes:
      - ./botpress/data:/botpress/data
    links:
      - postgres
    ports:
      - 3000:3000
    networks:
      - main_net 
